/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const UploadPageIndexLazyImport = createFileRoute('/upload-page/')()
const CreateListingIndexLazyImport = createFileRoute('/create-listing/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const UploadPageIndexLazyRoute = UploadPageIndexLazyImport.update({
  id: '/upload-page/',
  path: '/upload-page/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/upload-page/index.lazy').then((d) => d.Route),
)

const CreateListingIndexLazyRoute = CreateListingIndexLazyImport.update({
  id: '/create-listing/',
  path: '/create-listing/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/create-listing/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/create-listing/': {
      id: '/create-listing/'
      path: '/create-listing'
      fullPath: '/create-listing'
      preLoaderRoute: typeof CreateListingIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/upload-page/': {
      id: '/upload-page/'
      path: '/upload-page'
      fullPath: '/upload-page'
      preLoaderRoute: typeof UploadPageIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/create-listing': typeof CreateListingIndexLazyRoute
  '/upload-page': typeof UploadPageIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/create-listing': typeof CreateListingIndexLazyRoute
  '/upload-page': typeof UploadPageIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/create-listing/': typeof CreateListingIndexLazyRoute
  '/upload-page/': typeof UploadPageIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-listing' | '/upload-page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-listing' | '/upload-page'
  id: '__root__' | '/' | '/create-listing/' | '/upload-page/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CreateListingIndexLazyRoute: typeof CreateListingIndexLazyRoute
  UploadPageIndexLazyRoute: typeof UploadPageIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CreateListingIndexLazyRoute: CreateListingIndexLazyRoute,
  UploadPageIndexLazyRoute: UploadPageIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-listing/",
        "/upload-page/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/create-listing/": {
      "filePath": "create-listing/index.lazy.tsx"
    },
    "/upload-page/": {
      "filePath": "upload-page/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
